/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.dinosaur.gui;

import autonoma.dinosaurgame.Forest;
import java.awt.Graphics;
import java.awt.event.KeyEvent;

/**
 *
 * @author Kamii
 */
public class GameWindow extends javax.swing.JFrame {
    private Forest forest;
    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
        this.setSize(500,500);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
                switch(evt.getKeyCode())
        {
            case KeyEvent.VK_UP:
            case KeyEvent.VK_DOWN:
            case KeyEvent.VK_LEFT:
            case KeyEvent.VK_RIGHT:
                forest.handleKey(evt, getWidth(), getHeight());
            break;
            
            case KeyEvent.VK_A:
                forest.handleKey(evt, getWidth(), getHeight());
            break;
            
            case KeyEvent.VK_Q:
                exitGame();
            break;
        }
        
        repaint();
    }//GEN-LAST:event_formKeyPressed
    private void exitGame()
    {
        System.exit(0);
    }
    
    public void setGarden(Forest forest) {
        this.forest = forest;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); 
    
       forest.draw(g);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        GameWindow window = new GameWindow();
        
        Forest garden = new Forest(0, 0, window.getWidth(), window.getHeight());
        
        window.setGarden(garden);
        
        window.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
